### ISSUE TITLE
No data is fetched.

### ISSUE THREAD

**Issue by srinivasdamam** [codefoxes/firebase-admin#16]
@karthikax  @koushikbhushan I tried with my fire base credentials. Isn't showing any data or error. Also none of the queries are working.

**Comment by karthikax** [comment]
Hi @srinivasdamam can you please provide the steps to reproduce this.
Note:
* Make sure you imported config file (or entered connection details) correctly.
* Queries will not work unless app is connected to firebase.
* However app should show error if it can not establish connection. Will look into it.
Thanks

**Comment by karthikax** [comment]
[Version 1.0.1](https://firebaseadmin.com/releases) includes configuration validations and _**Test**_ connection button to test the firebase credentials in _**Create connection**_ window. Should fix the issue.
