### ISSUE TITLE
Malicious software in the download links Mac and Windows?

### ISSUE THREAD

**Issue by ADjenkov** [codefoxes/firebase-admin#23]
Hi guys, 

I really want to try out your product, but my My Symantec Protection gone crazy with the firebase-admin-windows.exe "Security risk detected: WS.Reputation.1". I've tried to install it on my MAC also , but the same. Am I doing something wrong? Should I be worried or should I ignore that threat warning? Or may be I should download the repo and try to run it by myself - any basic Installation istructions?

Thanks

**Comment by karthikax** [comment]
@ADjenkov You can ignore the warning. Find [more info](https://www.symantec.com/security_response/writeup.jsp?docid=2010-051308-1854-99) about threat.
We dint follow [application signing](https://github.com/Squirrel/Squirrel.Windows/blob/master/docs/using/application-signing.md) which we will fix soon.
Thanks
