### ISSUE TITLE
Scan Virus

### ISSUE THREAD

**Issue by mendesfelipe87** [codefoxes/firebase-admin#25]
Hello

When I download the executable to install the firebase admin, says that it haves a virus, Trojan:Win32/Detplock

so, this have a virus ?

**Comment by karthiknc** [comment]
Hi @mendesfelipe87 . Sorry for delay. It's a false positive.
Please find [virus information](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?Name=Trojan:Win32/Detplock).
But Firebase admin doesn't do any of those. You can go through the code to confirm. It definitely doesn't contain any virus. You can ignore the warning and install. However we will investigate why this happens. Thanks

**Comment by karthikax** [comment]
Hi @mendesfelipe87 . Sorry for delay. It's a false positive.
Please find [virus information](https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?Name=Trojan:Win32/Detplock).
But Firebase admin doesn't do any of those. You can go through the code to confirm. It definitely doesn't contain any virus. You can ignore the warning and install. However we will investigate why this happens. Thanks
