### ISSUE TITLE
Windows 10 install failed

### ISSUE THREAD

**Issue by 0nza1101** [codefoxes/firebase-admin#28]
Hi,
The installation failed on windows 10 giving me the following log outputs http://pastebin.com/80mtXiMX . 

Plus adwcleaner detect Firebase Admin as a malware. 
![capture](https://cloud.githubusercontent.com/assets/13056641/21470726/fc55fd80-ca95-11e6-8687-473272039a7c.PNG)

**Comment by karthikax** [comment]
Hi @0nza1101 
It looks like adwcleaners detects this as malware due to application signing. This is similar to #23 or #25 . I am trying to fix this. You can track it on #25 . Closing the issue here.
