### ISSUE TITLE
Typo on website

### ISSUE THREAD

**Issue by flowryaan** [codefoxes/firebase-admin#34]
Sorry if this is the wrong place, but I noticed a typo on your [website](https://firebaseadmin.com/)  and wanted to report it:

![image](https://cloud.githubusercontent.com/assets/8149519/24525809/aedce750-1593-11e7-8295-4da4e0e132c6.png)

I think you guys meant charge instead of "chanrge" :)

**Comment by karthikax** [comment]
Indeed. Thank you very much for the contribution @flowryaan Your help means a lot for us.
