### ISSUE TITLE
firebaseadmin.com is suspended

### ISSUE THREAD

**Issue by abdullahtariq1171** [codefoxes/firebase-admin#43]
[firebaseadmin.com](firebaseadmin.com) is suspended.

**Screenshot**
![image](https://user-images.githubusercontent.com/5623766/33977034-9950530c-e0ba-11e7-8d5a-c20e2e8eef82.png)

**Comment by karthikax** [comment]
I have fixed it a while ago. Thanks for reporting!

**Comment by mobitinker** [comment]
Seeing that it is suspended again 3/1/18
