### ISSUE TITLE
Is this project maintained or still working?

### ISSUE THREAD

**Issue by notflip** [codefoxes/firebase-admin#55]

**Comment by kristianalnaes** [comment]
Some still have trouble creating the initial connections, but as it stands, this broject seem to be working still. Using it semi-regular to look into a firebase I maintain.

**Comment by maciej-blyng** [comment]
Even though there is a pop-up after importing the private key saying the connection can't be established, it actually establishes a connection.

**Comment by karthikkp** [comment]
I have create FirebaseToolbox that does what firebase-admin does and more. It also helps you query and short hand actions on Firebase auth users. Find it here https://firebasetoolbox.com . It's also free. Just not open source yet
